### ISSUE TITLE
Does accept-language always produce the same result as i18n-abide?

### ISSUE THREAD

**Issue by philbooth** [mozilla/fxa-shared#13]
In practice there may be no problem here, I'm just filing this to make sure.

The mailer code in the auth server uses `i18n-abide` to parse the `Accept-Language` header. There is also code in the content server that uses `i18n-abide`. This repo uses a different module, `accept-language`. Do they always return the same result?

Is there any mileage in agreeing on one module across the board and using it going forward?

**Comment by vladikoff** [comment]
from https://github.com/mozilla/i18n-abide

**Comment by vladikoff** [comment]
For future let's try `accept-language` for new stuff, `i18n-abide` is not maintained.
