### ISSUE TITLE
Lint

### ISSUE THREAD

**Issue by philbooth** [mozilla/fxa-shared#16]
This repo has no linting set-up. Let's do something about it.

**Comment by vladikoff** [comment]
cc @deepti

**Comment by vladikoff** [comment]
@deeptibaghel let us know if this an interesting issue for you

**Comment by deeptibaghel** [comment]
@vladikoff yeah sure, i would be happy to work this :)

**Comment by vladikoff** [comment]
@deeptibaghel we can bring in the preset you already worked with and run eslint via 'npm run lint' , I suggest avoiding the grunt task
