### ISSUE TITLE
Move EMAIL_TYPES back to the content and auth servers

### ISSUE THREAD

**Issue by philbooth** [mozilla/fxa-shared#23]
#22 made me realise that I got the separation of concerns wrong with the Amplitude stuff. It's not right that people need to come and update this repo every time they add a new template to the auth server. The resolved email type should be passed in as a data property instead.

**Comment by vbudhram** [comment]
@philbooth Heh, yea I thought the same thing too, having to update here, publish new version, update other repo to use new version.
