### ISSUE TITLE
Moment is not using Arabic translations in last sync text

### ISSUE THREAD

**Issue by SafaAlfulaij** [mozilla/fxa-shared#33]
I have my browser languages set to “Arabic→English”. Technically it’s "ar:en".

Opening Firefox Accounts and checking the “Devices & Apps” section, you can see that `fromnow` is not using the Arabic translations. I can’t be sure if this is a server issue or an implementation issue. Checking Moment's code, Arabic translations [are available](https://github.com/moment/moment/blob/develop/locale/ar.js).

This is the production server. I couldn’t check the testing one as I don’t intend to connect anything with testing stuff :)
Screenshot:
![screenshot_2018-08-24 1](https://user-images.githubusercontent.com/3509617/44583487-3d561580-a7ae-11e8-823a-b8321995db3f.png)

EDIT: Sorry, I wasn’t sure if I should report about this here or to fxa-content-server.

**Comment by philbooth** [comment]
I'll dig into this to see how easy it is.

**Comment by philbooth** [comment]
Fix incoming for this, there's a couple of bugs in our language-selection logic.
