### ISSUE TITLE
`fy-NL` is fully translated and should be enabled.

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa-shared#9]
@Fjoerfoks informed us that the `fy-NL` strings are fully translated but are not being used in production. Our configuration has [fy](https://github.com/mozilla/fxa-shared/blob/9788b386533a7d11b4a4c5a49fe69e03397d4626/l10n/supportedLanguages.json#L24) enabled, but not `fy-NL`. 

`fy` is unavailable in Pontoon [2], only `fy-NL` - should we remove `fy` from the list of supportedLocales?

cc @jrgm and @jbuck

**Comment by vladikoff** [comment]
add fy-NL and copy THAT into `fy` if it is empty... 
https://github.com/mozilla/fxa-content-server-l10n/blob/master/scripts/before_prod_deploy.sh#L24

**Comment by vladikoff** [comment]
Fixed.
